stages:
  split_data:
    cmd: python src/data/split_data.py
    deps:
      - data/raw/raw.csv
    outs:
      - data/processed/X_train_scaled.npy
      - data/processed/X_test_scaled.npy
      - data/processed/y_train.npy
      - data/processed/y_test.npy

  normalize_data:
    cmd: python src/data/normalize_data.py
    deps:
      - data/processed/X_train.npy
      - data/processed/X_test.npy
    outs:
      - data/processed/X_train_scaled.npy
      - data/processed/X_test_scaled.npy

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
      - data/processed/X_train_scaled.npy
      - data/processed/y_train.npy
    outs:
      - models/best_params.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - data/processed/X_train_scaled.npy
      - data/processed/y_train.npy
      - models/best_params.pkl
    outs:
      - models/trained_model.pkl

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - data/processed/X_test_scaled.npy
      - data/processed/y_test.npy
      - models/trained_model.pkl
    outs:
      - data/predictions.npy
      - metrics/scores.json
